### ISSUE TITLE
Cannot loop through a hierachy of groups within Gitlab

### ISSUE THREAD

**Issue by yacine-maghezzi-sonarsource** [SonarSource/sonar-loc-count#11]
When having a hierarchy of groups within Gitlab, the script doesn't work. 
Hint : Use full_path instead of path

**Comment by brian-cipollone-sonarsource** [comment]
@yacine-maghezzi-sonarsource - Fixed with #12  ?

**Comment by yacine-maghezzi-sonarsource** [comment]
No unfortunately, work was done over azure but not gitlab script

**Comment by colussim** [comment]
this issue is solved with the new version of the script
