### ISSUE TITLE
If folder already exists, ask for confirmation on exit with error, prevent data loss in cleanup

### ISSUE THREAD

**Issue by ziaulrehman40** [SonarSource/sonar-loc-count#17]
I lost precious data when i used github script and i had same named folders in the folder i ran the script in. As it tried to clone in same folder, gave warning but didn't stop or warn that data can be lost.

Ended up loosing some of my data.

**Comment by emmanuel-colussi-sonarsource** [comment]
Very sorry that you lost valuable data, but the script is supposed to run in a workspace without data. We take note of this problem and will modify the code in this sense.
