### ISSUE TITLE
Rate limiting on github.com

### ISSUE THREAD

**Issue by yassinecc** [SonarSource/sonar-loc-count#18]
`curl -s -u github_pat_xxxx: https://api.github.com/repos/my_org/my_repo/branches                     `       
gives                     
```
{                                                                                                        
  "message": "API rate limit exceeded for $MY_IP. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",                               
  "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"                                                                                                             
}
```

I had to change the curl to
`curl -s --header "Authorization: Bearer github_pat_xxxx" https://api.github.com/repos/my_org/my_repo/branches`

Can the script use an authentication method with a high rate limit?

**Comment by sylvain-combe-sonarsource** [comment]
Hi @yassinecc 
thanks for your interest in the script.
curl -u should be functionally equivalent to setting the authorization token yourself.
And there seems to be a glitch [there in the GH script](https://github.com/SonarSource/sonar-loc-count/blob/bca9ff25eedebcb9458c63efcc1dca286fc24e90/github_com.sh#L73).
Can you try to update this line as follows:

**Comment by yassinecc** [comment]
Hello @sylvain-combe-sonarsource 

Yes it works fine :+1: Should I make a PR for it?
