### ISSUE TITLE
github_com.sh only counting LOC for up to 30 repositories

### ISSUE THREAD

**Issue by diasdm** [SonarSource/sonar-loc-count#6]
Hi,

The default API used in _github_com.sh_ (`https://api.github.com/orgs/${org}/repos`) will only list up to 30 repositories.
Using `https://api.github.com/orgs/${org}/reposrepos?per_page=100` we can get up to 100.

I've ended up using Github cli, `gh repo list ${org} -L 1000 --json name,defaultBranchRef`, it gives us up to 1000.

**Comment by sylvain-combe-sonarsource** [comment]
Hi @diasdm 
thanks for reporting the issue. Can you please confirm if it is fixed for you as well.
Cheers
Sylvain
